# Generated by Django 6.0.4 on 2026-04-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('citizen_scientist', 'Citizen Scientist'), ('researcher', 'Researcher'), ('moderator', 'Moderator')], default='citizen_scientist', max_length=30),
        ),
    ]
