# Generated by Django 6.0.4 on 2026-04-14 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('dismissed', 'Dismissed'), ('mark_under_review', 'Marked under review'), ('remove_submission', 'Submission removed')], default='pending', max_length=25),
        ),
        migrations.AddField(
            model_name='flag',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flag',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL),
        ),
    ]
