# Generated by Django 6.0.4 on 2026-04-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255)),
                ('common_name', models.CharField(blank=True, max_length=255)),
                ('taxon_class', models.CharField(blank=True, max_length=100)),
                ('conservation_status', models.CharField(blank=True, max_length=100)),
                ('is_endemic', models.BooleanField(default=False)),
                ('reference_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['common_name', 'scientific_name'],
            },
        ),
    ]
